### ISSUE TITLE
Two tanks were assimilated that both previously had contents...

### ISSUE THREAD

**Issue by Cherry** [carrotengineer/EnderTech#46]
Screenshot: http://jross.me/l/jmnvh

Users noted that the server appeared to "hang" momentarily when these errors were displayed. 
Mod list: http://jross.me/l/2l37r (Bytesize 0.0.9 - http://www.atlauncher.com/pack/Bytesize)

Happy to provide any further information if necessary.

**Comment by voxelcarrot** [comment]
Interesting. The error message is there mainly to help with debugging - in all of these cases it looks like something really strange is happening with the order that the blocks in the tank are loaded. This is likely related to the "hang" - I don't think EnderTech is causing the lag, but it is being affected by it.

If everything seems fine with the tanks, it's nothing to worry about. I'll probably disable this error message if it looks like the two "choices" are identical (as is the case here).

**Comment by Cherry** [comment]
Interesting - thanks for the update. If there is any further debugging or information we can provide, we'd be happy to do so.

**Comment by voxelcarrot** [comment]
Is it at all possible to try a different version of the mod on your server? acaab6e tries to check for this case, and outputs a different 'error' message: "WARNING: Two tanks were assimilated that both previously had the same contents. This is probably OK, and sometimes happens with server lag, but is worth noting.".

If you can: https://hopper.bunnies.io/job/EnderTech/386/ - otherwise wait for it to make its way through to the ATLauncher system, probably in a few weeks.

**Comment by Cherry** [comment]
Certainly! I assume this specific build won't cause problems for clients on 0.3.2.382?

**Comment by voxelcarrot** [comment]
Ah sadly it needs the same version on both sides. I'll stick it on ForgeCraft and let it settle for a little while before I promote it to 'stable'. I wouldn't worry about the errors - but let me know if it looks like anything got duplicated or lost.

**Comment by Cherry** [comment]
Ah okay, I assumed as much, but wanted to make sure. I'll see about pushing an update to Bytesize when you've pushed it stable. Thanks very much for the assistance!

**Comment by voxelcarrot** [comment]
Build 386 is now marked as stable on Curse Forge :) http://minecraft.curseforge.com/mc-mods/223428-endertech/files/2237981

**Comment by Cherry** [comment]
Thanks for the heads up! :)

**Comment by voxelcarrot** [comment]
So, I double checked the amount of output in "Debug" mode, and it turns out I left some debugging logging in which made the amount of output really ridiculous.

Build 388 fixes it and removes logging in "non destructive" cases: http://minecraft.curseforge.com/mc-mods/223428-endertech/files/2238351 - I strongly recommend updating when you can

**Comment by Cherry** [comment]
Whoops, lucky I didn't push it live just yet then! Thanks for the heads up once again, much appreciated. :)
