### ISSUE TITLE
Charge Pad side textures show as the texture atlas

### ISSUE THREAD

**Issue by RoloEdits** [carrotengineer/EnderTech#54]
![2015-07-06_23 43 22](https://cloud.githubusercontent.com/assets/12489689/8540263/d7bf2ac8-2438-11e5-8c03-72aba1749b30.png)

![2015-07-06_23 41 18](https://cloud.githubusercontent.com/assets/12489689/8540264/db39e5f8-2438-11e5-9cfc-bd8a0a538aad.png)

![2015-07-06_23 41 33](https://cloud.githubusercontent.com/assets/12489689/8540268/de53ad46-2438-11e5-8d65-907324b8e10a.png)

**Comment by usafphoenix** [comment]
also getting an instance of this, texture on all but front-face is a collation of ALL other minecraft textures combined.

**Comment by Walshie1980** [comment]
I get the same issue with MystcraftNEI and SPACore installed.  When they are removed textures are fine again.

**Comment by usafphoenix** [comment]
I can confirm removal of mystcraftNEI and SPAcore for my pack fixing issue for me, as well.

**Comment by RoloEdits** [comment]
i dont have mystcraft nei so its with SpACore

**Comment by RoloEdits** [comment]
Just found this on the curse page.


"Known Issues

Does not work with FastCraft due to an issue with how it handles Texture atlases."

**Comment by voxelcarrot** [comment]
I tried to reproduce this but couldn't. I don't do anything strange with textures - they're all pretty basic (minus the tank rendering), so I'd be surprised if other mods didn't have similar issues in the same pack.

**Comment by RoloEdits** [comment]
I just removed SpACore and it fixed it, sorry for the trouble.

**Comment by BluSunrize** [comment]
This is an error createable by using Immersive Engineering, as shown here:
https://github.com/BluSunrize/ImmersiveEngineering/issues/352

The reason for this is that in the texture stitching event, you only check if the given texture map uses the ID 1. You do not check if it uses 0, for Items.
Since IE uses a custom texturemap for its revolvers, it tries to stitch into that.

https://github.com/carrotengineer/EnderTech/blob/9eeacc8aed1707d0d4858357a638dd2ce222483c/src/main/java/io/endertech/proxy/ClientProxy.java#L61

You should change this line to "if (event.map.getTextureType() != 0) return;"

Note that using a custom texturemap is not hacky or anything, rather it's something few developers do, but it's a perfectly "normal" thing to do with forge. So you should check for the map ID you want, not for the ones you don't want to avoid this issue.

best regards =3

**Comment by carrotengineer** [comment]
Great, thanks for the heads up and the fix!

Could someone please try out this build and let me know if it works? I'll try it and upload to Curse today. https://hopper.bunnies.io/job/EnderTech/392/

**Comment by carrotengineer** [comment]
Had time to check it before work, there's a new stable build up on Curse (392) and it should be out of review soon :)
