### ISSUE TITLE
Exchanger duplication exploit when used in an Autonomous Activator

### ISSUE THREAD

**Issue by RayHell** [carrotengineer/EnderTech#57]
There's an exploit when you put the resonant exchanger into an autonomous activator (Thermal Expansion) with a block in front. It duplicate the block without removing it from the activator inventory.

**Comment by carrotengineer** [comment]
Are you using a modpack?

**Comment by RayHell** [comment]
Yes FTB Infinity version 1.8.2

**Comment by CaBz** [comment]
Specifically, the .jar used is: **EnderTech-1.7.10-0.3.2.388.jar**

**Comment by carrotengineer** [comment]
Thanks, I'll investigate when I have some free time this weekend.

**Comment by carrotengineer** [comment]
Tried to reproduce this with the latest FTB Infinity (1.10.1/recommended) and couldn't. I suspect it's a modpack issue that has already been fixed.

Here's what I tried: http://imgur.com/a/l9X4x

**Comment by RayHell** [comment]
Sorry I read my comment and it wasn't clear at all. I've modify it and made a video of the exploit.
https://www.youtube.com/watch?v=T-VkzcbkLiQ&feature=youtu.be

**Comment by carrotengineer** [comment]
Great, thanks. I'll investigate some more but this does seem very weird.

**Comment by carrotengineer** [comment]
So, the Autonomous Activator lies about actually removing an item, when it's the last one in the stack. Don't ask me why.

Instead of just blacklisting FakePlayers (so you couldn't use it at all), I'm going to try making it so it doesn't consume the last item in a stack, when used by a FakePlayer.

Could you try out build 394 and let me know if it seems to work OK please?

https://hopper.bunnies.io/job/EnderTech/394/

**Comment by CaBz** [comment]
Just tried it on a single player game. It doesn't duplicate items. In fact, it doesn't replace the block in front at all (even though there's one item in the Autonomous Activator). I don't know if this was the desired behavior?

The setup: http://i.imgur.com/m9DAgeV.png
The content: http://i.imgur.com/QlnRQvE.png

Thanks!

**Comment by carrotengineer** [comment]
@CaBz yep, that's intentional. It won't replace the last block in the stack (because the Autonomous Activator lies about it being consumed, making the Exchanger think it was safe to replace but results in a duplication).

You'll need more than one in a stack to do the exchange. I couldn't figure out a way around it, and the only alternative seems to be blacklisting FakePlayers all together.

**Comment by CaBz** [comment]
I trust your judgement on that one.

Thank you for the quick reply!

**Comment by carrotengineer** [comment]
The build just went live on CurseForge, so I'm going to close this for now. http://minecraft.curseforge.com/mc-mods/223428-endertech/files/2254885
