### ISSUE TITLE
Silk Touch for Exchanger

### ISSUE THREAD

**Issue by Tergiver** [carrotengineer/EnderTech#59]
I would love to see Silk Touch added for the Resonant and Creative versions of the Exchanger. Maybe I'm just spoiled by the Thaumcraft Equal Trade wand accessory, but it would also make inventory management a bit easier since the exchange will always be one-to-one (one block for one block rather than one block for 1 or more items).

**Comment by carrotengineer** [comment]
Yep - I was thinking about the best way to do this the other day.

I'm not familiar with the enchantment system, but that might be a good way to do it. Eg: you enchant the Exchanger with Silk Touch, and that adds a hard multiplier (like 1.2x) to the block cost.

I'm also very tempted to give Silk Touch for free - since that's what it's actually conceptually doing. I could enable Silk Touch by default and have a config option to go back to the old behaviour.

**Comment by carrotengineer** [comment]
Ok, I made a build with Silk Touch behaviour by default, and a configuration option for it in `items.cfg`.

Could you give it a try please? https://hopper.bunnies.io/job/EnderTech/399/

**Comment by Tergiver** [comment]
You sir, are awesome!

A few hours ago I was wishing the Exchanger had Silk Touch, and now I'm playing with it!

No more dumping trips because Mixed Compound gives you clay, sand, and gravel when you break it :)

**Comment by carrotengineer** [comment]
So, working as expected? If so I'll probably put a build straight on Curse Forge, but I'm almost certain there might be dupe bugs floating around. Hard to know if the approach is right without people getting their hands on it first!

**Comment by Tergiver** [comment]
I exchanged one large room with a mix of blocks: the aforementioned Mixed Compound, Coal, Iron, Copper, Lumenite, etc. for three different blocks: Stone, and two forms of Chisel 2 cobblestone.

I can't say there's no dupe bugs, but I'll keep using it.

Thank you!

**Comment by carrotengineer** [comment]
Ok, thanks. I'll stick a build on Curse if things seem alright - I couldn't break it so it's probably fine :)

**Comment by carrotengineer** [comment]
Build will be here when it gets approved: http://minecraft.curseforge.com/mc-mods/223428-endertech/files/2256741
